# Generated by Django 4.2.30 on 2026-04-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Rachit', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('professional_summary', models.TextField(blank=True)),
                ('template', models.CharField(choices=[('modern', 'Modern Minimal'), ('executive', 'Executive Pro'), ('creative', 'Creative Vivid'), ('tech', 'Tech Developer'), ('elegant', 'Elegant Classic'), ('bold', 'Bold Impact')], default='modern', max_length=20)),
                ('experience_json', models.TextField(default='[]')),
                ('education_json', models.TextField(default='[]')),
                ('skills_json', models.TextField(default='[]')),
                ('projects_json', models.TextField(default='[]')),
                ('certifications_json', models.TextField(default='[]')),
                ('languages_json', models.TextField(default='[]')),
                ('achievements_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV Profile',
                'verbose_name_plural': 'CV Profiles',
            },
        ),
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('overall_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('format_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('skills_match_score', models.IntegerField(default=0)),
                ('matched_keywords', models.TextField(default='[]')),
                ('missing_keywords', models.TextField(default='[]')),
                ('suggestions', models.TextField(default='[]')),
                ('detailed_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='cv_app.cvprofile')),
            ],
            options={
                'verbose_name': 'ATS Score',
                'verbose_name_plural': 'ATS Scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
