# Generated by Django 4.2.30 on 2026-04-24 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cvprofile',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern Minimal'), ('atspro', 'ATS Pro'), ('clean', 'Clean Simple'), ('executive', 'Executive Pro'), ('tech', 'Tech Developer'), ('creative', 'Creative Vivid'), ('elegant', 'Elegant Classic'), ('bold', 'Bold Impact')], default='modern', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20)),
                ('daily_ats_checks', models.IntegerField(default=0)),
                ('last_ats_check_date', models.DateField(blank=True, null=True)),
                ('cv_limit', models.IntegerField(default=5)),
                ('cv_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
